POSTGRES_USER = "agentes"
POSTGRES_PASSWORD = "agentes"
POSTGRES_DB = "neondb"
POSTGRES_HOST = "ep-bitter-frog-b2xug8t1.c-6.eu-central-1.aws.neon.tech"
POSTGRES_PORT = "5432"
POSTGRES_SSLMODE = "require"